name: CI
on:
  push:
  workflow_dispatch:

jobs:
  crystal-style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    name: "${{ !matrix.stable && '🚧 ' || ''}}crystal: ${{ matrix.crystal }}, etcd: ${{ matrix.etcd }}"
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - 1.1.1
          - 1.2.2
        etcd:
          - 3.3
          - 3.4
          - 3.5
        stable: [true]
        include:
          - crystal: nightly
            stable: false
            etcd: 3.3
          - crystal: nightly
            stable: false
            etcd: 3.4
          - crystal: nightly
            stable: false
            etcd: 3.5
    runs-on: ubuntu-latest
    services:
      etcd:
        image: bitnami/etcd:${{ matrix.etcd }}
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: "yes"
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - run: shards install
      - run: crystal spec --order random
